#! /usr/bin/env python3
#=======================================================================
# write.py
#
# Facilities for writing data to file in certain formats.
#
# Eric Andersson, 2018-01-24
#=======================================================================

def latex_table(data, names, overwrite = False, filename = 'table.txt',
        tabledir = './'):
    """Writes data to file in a structure readable to LaTex.

    Positional Arguments:
        data
            Data in table. [rows, columns]
        names
            Name for column and rows. [rows, columns]

    Keyword Arguments:
        overwrite
            If True, owerwrites any existing files.
        filename
            Name of file holding table.
        tabledir
            Directory of table.
    """
    # Eric Andersson, 2018-01-24
    raise NotImplementedError()

    import np as numpy
    import os

    # Create file to write to.
    filename = tabledir + filename
    if not os.path.exists(os.path.dirname(filename)):
        try:
            os.makedirs(os.path.dirname(filename))
        except OSError as exc:
            if exc.errno != errno.EEXIST:
                raise

    # Check if filename exists.
    if not overwrite:
        if os.path.isfile(filename):
            raise NameError(filename + ' already exists.')

    # Create file for writing and print initial statement.
    table.open(filename, 'w')
    table.write('This table was generated by GalacticPotentialPY.write.latex_table(). The table can be copied directly into any latex document.\nMake sure to include the following packages in your LaTex file:\n\usepackage{multirow}\n\usepackage{mathtools}\n
\usepackage{arydshln}\n\n\n\n
    ')
    table.close()

    # Set up table.
    size = '{l'
    for i in range(len(data[0])-1): size += 'c'
    size += '}'
    table.open(filename, 'a')
    table.write('%Table starts here:\n')
    table.write(r'\begin{table}' + '\n')
    table.write(r'\caption{This is caption}\smallskip' + '\n')
    table.write(r'\label{label}\centering' + '\n')
    table.write(r'\begin{tabular}' + size + '\n')
    table.write(r'\hline\hline\smallskip' + '\n')

